version: "3.7"

services:
  angular: # name of the first service
    build: front # specify the directory of the Dockerfile
    ports:
      - "4200:80" # specify port mapping
    #restart: unless_stopped
    depends_on:
      - express
    links:
      - express
    stdin_open: true
    networks:
      - my-network
 
  express: # name of the second service
    build: server # specify the directory of the Dockerfile
    ports:
      - "4201:3000" #specify ports mapping
    depends_on:
      - database # link this service to the database service
    #restart: unless_stopped 
    networks:
      - my-network
  
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27019:27017" # specify port forwarding
    #restart: unless_stopped
    networks:
      - my-network

networks:
  my-network:
    driver: bridge