version: "3.7"

services:
  angular: # name of the first service
    build: front # specify the directory of the Dockerfile
    # ports:
    #   - "4000:4000" # specify port mapping
    voulmes:
      - ./front:/usr/app/node_modules/
 
  express: # name of the second service
    build: 
      context: server
      dockerfile: Dockerfile
    depends_on:
      - database # link this service to the database service
    #restart: unless_stopped 
    env_file:
      - ./server/.env
    voulmes:
      - ./server:/usr/server/node_modules/
  
  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27040:27017" # specify port forwarding

  nginx: #name of the fourth service
    build: 
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx_mean
    restart: always
    ports:
      - "4202:5000" #specify ports forewarding
    depends_on:
      - express
      - angular